repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-mypy
        additional_dependencies: [tree-sitter==0.23.0, tree-sitter-language-pack==0.2.0, mypy==1.11.2, torch==2.4.1, types-tqdm==4.66.0.20240417]
        args: ["--strict"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'
    hooks:
    - id: mypy
      additional_dependencies: [tree-sitter==0.23.0, tree-sitter-language-pack==0.2.0]
      args: [--strict]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
