repos:
  - repo: local
    hooks:
    - id: ruff_lint
      name: Linting with ruff
      entry: sh -c "ruff check ."
      language: system

    - id: ruff_format
      name: Checking formatting with ruff
      entry: sh -c "ruff format --check ."
      language: system

    - id: mypy_nb
      additional_dependencies: [tree-sitter==0.23.0]
      name: Type checking notebooks with mypy
      entry: nbqa mypy
      language: python

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.11.2'
      hooks:
      - id: mypy
        additional_dependencies: [tree-sitter==0.23.0, tree-sitter-language-pack==0.2.0]
        args: [--strict]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
