repos:
  - repo: local
    hooks:
    - id: ruff_lint_src
      name: Linting source files with ruff
      entry: sh -c "ruff check *.py"
      language: system

    - id: ruff_format_src
      name: Checking formatting of source files with ruff
      entry: sh -c "ruff format --check *.py"
      language: system

    - id: ruff_nb
      name: Linting notebooks with ruff
      entry: sh -c "nbqa ruff *.ipynb"
      language: system

    - id: mypy_nb
      additional_dependencies: [tree-sitter==0.23.0]
      name: Type checking notebooks with mypy
      entry: nbqa mypy
      language: python

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.11.2'
      hooks:
      - id: mypy
        additional_dependencies: [tree-sitter==0.23.0, tree-sitter-language-pack==0.2.0]
        args: [--strict]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
