name: Type Checking
on: push
jobs:
  lint:
    name: Static Type Checking With mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Run mypy on Python source files
        run: mypy .
      - name: Run mypy on Jupyter Notebooks
        run: nbqa mypy .
