name: Ruff
on: push
jobs:
  lint:
    name: Lint Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Lint Python source files
        run: ruff check --output-format=github .
      - name: Lint Jupyter Notebooks
        run: nbqa ruff check --output-format=github *.ipynb

  format:
    name: Check Source Formatting
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Check Formatting for Python source files
        run: ruff format --check .
      - name: Check Formatting for Jupyter Notebooks

  nbqa:
    name: Ruff NBQA
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Run ruff on Jupyter Notebooks
        run: nbqa ruff *.ipynb
