name: Ruff
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Lint files
        run: ruff check --output-format=github .

  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Check Formatting for Python source files
        run: ruff format --check .
